runtime: python
api_version: 1
env: flex
entrypoint: gunicorn -b :$PORT main:app
threadsafe: true

# [START handlers]
handlers:
- url: /static
  static_dir: static
- url: /.*
  script: main.app
# [END handlers]

env_variables:
    CLOUD_STORAGE_BUCKET: kchylee1
    MEMCACHE_SERVER: memcached-14094.c1.us-central1-2.gce.cloud.redislabs.com:14094
  # If you are using a third-party or self-hosted Memcached server with SASL
  # authentiation enabled, uncomment and fill in these values with your
  # username and password.
    MEMCACHE_USERNAME: boundingbox
    MEMCACHE_PASSWORD: boundingbox

  