runtime: python
api_version: 1
env: flex
entrypoint: gunicorn -b :$PORT main:app
threadsafe: true

# [START handlers]
handlers:
- url: /static
  static_dir: static
- url: /.*
  script: main.app
# [END handlers]

env_variables:
    CLOUD_STORAGE_BUCKET: kchylee1